### ISSUE TITLE
Setter method to adjust orientation on config change

### ISSUE THREAD

**Issue by skorudzhiev** [LittleMango/StackLayoutManager#12]
I noticed that there is no setter method to adjust layout orientation after the manager is already initialized. 
Any suggestions?

**Comment by LittleMango** [comment]
@skorudzhiev Since orientation is associated with animation and layout, it is not easy to handle the setter method, and you can achieve a similar effect by call `scrollToPosition` method after set new layoutManager
```
mStackLayoutManager = new StackLayoutManager(ScrollOrientation.LEFT_TO_RIGHT);
mRecyclerView.setLayoutManager(mStackLayoutManager);
mRecyclerView.scrollToPosition(targetPosition);
```

**Comment by skorudzhiev** [comment]
Thanks for your reply!
I will handle it this way :)
