### ISSUE TITLE
Any idea to make scroll more easier?

### ISSUE THREAD

**Issue by adeldolgov** [LittleMango/StackLayoutManager#13]
Hello! How can i make card scrolling more "easier"?

**Comment by LittleMango** [comment]
@adeldolgov Hello, I'm not quite clear about your question, could you describe it in detail?

**Comment by adeldolgov** [comment]
@LittleMango try to fast scoll items, sometimes it will not scroll :(

**Comment by adeldolgov** [comment]
@LittleMango oh sorry, that's my fault. 
I had recyclerview with your layout manager at bottom of bottomsheet. 
I fixed it now, now everything works great. Thanks!
