### ISSUE TITLE
Items are not visible at the bottom

### ISSUE THREAD

**Issue by Jothi-Vtech** [LittleMango/StackLayoutManager#6]
I have used `Match_parent` as width and height for the RecyclerView item view.

 I have set visible count as 5 and Direction as BOTTOM_TO_TOP

 But it is not showing the 4 items at the bottom. If I set particular height, Then it is visible. I think, It is cropped. Can anyone help me!!!

**Comment by LittleMango** [comment]
I have change [image_card.xml](https://github.com/LittleMango/StackLayoutManager/blob/master/sample/src/main/res/layout/image_card.xml)'s width and height to `match_parent` as follow:
```
<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    app:cardElevation="4dp"
    app:cardCornerRadius="10dp"
    >
    <ImageView
        android:id="@+id/imageView"
        android:scaleType="fitXY"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
    </ImageView>
    <TextView
        android:id="@+id/textView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:textSize="50sp"/>
</android.support.v7.widget.CardView>
```

and I find it behavior normal that all the item can be see.

you can try it as I do at first.

**Comment by Jothi-Vtech** [comment]
Thanks, But I solved it by subtracting 10 for the bottom value: 

       `int bottom = top + stackLayoutManager.getDecoratedMeasuredHeight(itemView) - 10;`

I don't know why but match_parent made an issue in my case.
